name: Build and publish

on:
    push:
        tags:
            - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            include:
                - os: ubuntu-latest
                # - os: windows-latest
                # - os: macos-latest


    steps:
        - uses: actions/checkout@v2

        - run: mkdir -v out

        - name: Bulild for Linux
          if: matrix.os == 'ubuntu-latest'
          run: gcc code-HWCRO.c -o out/code-HWCRO -Wall -O2 -s -static

        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: out/code-HWCRO
              asset_name: ${{ matrix.asset_name }}
              tag: ${{ github.ref }}
